project:
  type: website
  output-dir: docs

website:
  title: "Variation in the rate of ageing"
  navbar:
    left:
      - href: home.qmd
        text: Home page
      - href: data_collation.qmd
        text: Data collation
      - href: GWAS.qmd
        text: Genetic analysis

    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://tomkeaney.github.io/DGRP_lifespan_inequality

format:
  html:
      theme: Minty # browse these here: https://quarto.org/docs/output-formats/html-themes.html
      max-width: 1800px # adjust if your plots don't fit or you want more or less whitespace
      toc: true # do you want a table of contents, by default it floats as you scroll
      toc-location: left # where should it be displayed
      toc-title: "Sections"
      code-fold: true # fold code up for neater display
      code-tools: true # add a button at the top of doc to show all code
      code-summary: "Show the code"
      smooth-scroll: true
      embed-resources: true # output doc contains all info needed to display html
      fig-format: png
